#pragma once

#define TERRAIN_SIZE 20
#define TERRAIN_AMPLIFIER 200
#define CHUNK_SIZE 32
#define CHUNK_CUBIC_SIZE (CHUNK_SIZE * CHUNK_SIZE * CHUNK_SIZE)
#define CHUNKING_RADIUS 6
#define CHUNKING_DELETION_RADIUS CHUNKING_RADIUS + 2
