#pragma once

#define TERRAIN_SIZE 20
#define TERRAIN_AMPLIFIER 200
#define CHUNK_SIZE 28
#define CHUNKING_RADIUS 8
#define CHUNKING_THREADS 4
#define CHUNKING_DELETION_OFFSET 2

#define WORLD_SIZE (CHUNK_SIZE * TERRAIN_SIZE)
#define CHUNKING_DELETION_RADIUS (CHUNKING_RADIUS + CHUNKING_DELETION_OFFSET)
#define CHUNK_CUBIC_SIZE (CHUNK_SIZE * CHUNK_SIZE * CHUNK_SIZE)