#pragma once

#define TERRAIN_SIZE 20
#define TERRAIN_HEIGHT 256
#define CHUNK_SIZE 16
#define CHUNK_CUBIC_SIZE (CHUNK_SIZE * CHUNK_SIZE * TERRAIN_HEIGHT)
#define CHUNKING_RADIUS 8
#define CHUNKING_DIAMETER (CHUNKING_RADIUS * 2)
#define CHUNKING_SIZE (CHUNKING_DIAMETER * CHUNKING_DIAMETER)