#pragma once

const int CHUNK_SIZE = 16;
const int OCTREE_MAX_LEVEL = 2;

const int CHUNK_SIZE_MINUS_ONE = (CHUNK_SIZE - 1);
const int CHUNK_CUBIC_SIZE = (CHUNK_SIZE * CHUNK_SIZE * CHUNK_SIZE);
const int OCTREE_LENGTH = OCTREE_MAX_LEVEL * OCTREE_MAX_LEVEL;
const int OCTREE_FRUSTUM_CULLING = CHUNK_SIZE * 2;